country_region={'AF':'APAC',
'AL':'EMEA',
'DZ':'EMEA',
'AS':'APAC',
'AD':'EMEA',
'AO':'EMEA',
'AI':'APAC',
'AG':'APAC',
'AR':'LATAM',
'AM':'EMEA',
'AW':'APAC',
'AU':'UCAN',
'AT':'EMEA',
'AZ':'EMEA',
'BS':'APAC',
'BH':'EMEA',
'BD':'APAC',
'BB':'APAC',
'BY':'EMEA',
'BE':'EMEA',
'BZ':'LATAM',
'BJ':'EMEA',
'BM':'APAC',
'BT':'APAC',
'BO':'LATAM',
'BA':'EMEA',
'BW':'EMEA',
'BR':'LATAM',
'VG':'APAC',
'BN':'APAC',
'BG':'EMEA',
'BF':'EMEA',
'BI':'EMEA',
'KH':'APAC',
'CM':'EMEA',
'CA':'UCAN',
'CV':'EMEA',
'KY':'APAC',
'CF':'EMEA',
'TD':'EMEA',
'CL':'LATAM',
'CN':'APAC',
'CX':'APAC',
'CC':'APAC',
'CO':'LATAM',
'KM':'APAC',
'CG':'EMEA',
'CK':'APAC',
'CR':'LATAM',
'CI':'EMEA',
'HR':'EMEA',
'CU':'APAC',
'CY':'EMEA',
'CZ':'EMEA',
'DK':'EMEA',
'DJ':'EMEA',
'DM':'APAC',
'DO':'APAC',
'EC':'LATAM',
'EG':'EMEA',
'SV':'LATAM',
'GQ':'EMEA',
'ER':'EMEA',
'EE':'EMEA',
'ET':'EMEA',
'FK':'LATAM',
'FO':'EMEA',
'FJ':'APAC',
'FI':'EMEA',
'FR':'EMEA',
'GF':'LATAM',
'PF':'APAC',
'GA':'EMEA',
'GM':'EMEA',
'GE':'EMEA',
'DE':'EMEA',
'GH':'EMEA',
'GI':'EMEA',
'GR':'EMEA',
'GL':'EMEA',
'GD':'APAC',
'GP':'APAC',
'GU':'APAC',
'GT':'LATAM',
'GN':'EMEA',
'GW':'EMEA',
'GY':'LATAM',
'HT':'APAC',
'VA':'EMEA',
'HN':'LATAM',
'HU':'EMEA',
'IS':'EMEA',
'IN':'APAC',
'ID':'APAC',
'IR':'EMEA',
'IQ':'EMEA',
'IE':'EMEA',
'IL':'EMEA',
'IT':'EMEA',
'JM':'APAC',
'JP':'APAC',
'JO':'EMEA',
'KZ':'APAC',
'KE':'EMEA',
'KI':'APAC',
'KP':'APAC',
'KR':'APAC',
'KW':'EMEA',
'KG':'APAC',
'LA':'APAC',
'LV':'EMEA',
'LB':'EMEA',
'LS':'EMEA',
'LR':'EMEA',
'LY':'EMEA',
'LI':'EMEA',
'LT':'EMEA',
'LU':'EMEA',
'MK':'EMEA',
'MG':'APAC',
'MW':'EMEA',
'MY':'APAC',
'MV':'APAC',
'ML':'EMEA',
'MT':'EMEA',
'MH':'APAC',
'MQ':'APAC',
'MR':'EMEA',
'MU':'APAC',
'YT':'APAC',
'MX':'LATAM',
'FM':'APAC',
'MD':'EMEA',
'MC':'EMEA',
'MN':'APAC',
'MS':'APAC',
'MA':'EMEA',
'MZ':'EMEA',
'MM':'APAC',
'NA':'EMEA',
'NR':'APAC',
'NP':'APAC',
'NL':'EMEA',
'AN':'APAC',
'NC':'APAC',
'NZ':'UCAN',
'NI':'LATAM',
'NE':'EMEA',
'NG':'EMEA',
'NU':'APAC',
'NF':'APAC',
'MP':'APAC',
'NO':'EMEA',
'OM':'EMEA',
'PK':'APAC',
'PW':'APAC',
'PA':'LATAM',
'PG':'APAC',
'PY':'LATAM',
'PE':'LATAM',
'PH':'APAC',
'PN':'APAC',
'PL':'EMEA',
'PT':'EMEA',
'PR':'APAC',
'QA':'EMEA',
'RE':'APAC',
'RO':'EMEA',
'RU':'APAC',
'RW':'EMEA',
'KN':'APAC',
'LC':'APAC',
'PM':'UCAN',
'VC':'APAC',
'SM':'EMEA',
'ST':'EMEA',
'SA':'EMEA',
'SN':'EMEA',
'SC':'APAC',
'SL':'EMEA',
'SG':'APAC',
'SK':'EMEA',
'SI':'EMEA',
'SB':'APAC',
'SO':'EMEA',
'ZA':'EMEA',
'ES':'EMEA',
'LK':'APAC',
'SD':'EMEA',
'SR':'LATAM',
'SJ':'EMEA',
'SZ':'EMEA',
'SE':'EMEA',
'CH':'EMEA',
'SY':'EMEA',
'TW':'APAC',
'TJ':'APAC',
'TZ':'EMEA',
'TH':'APAC',
'TG':'EMEA',
'TK':'APAC',
'TO':'APAC',
'TT':'APAC',
'TN':'EMEA',
'TR':'EMEA',
'TM':'APAC',
'TC':'APAC',
'TV':'APAC',
'UG':'EMEA',
'UA':'EMEA',
'AE':'EMEA',
'UK':'EMEA',
'GB':'EMEA',
'US':'UCAN',
'UY':'LATAM',
'UZ':'APAC',
'VU':'APAC',
'VE':'LATAM',
'VN':'APAC',
'VI':'APAC',
'WF':'APAC',
'EH':'EMEA',
'WS':'APAC',
'YE':'EMEA',
'ZR':'EMEA',
'ZM':'EMEA',
'ZW':'EMEA',
'HK':'APAC',
'MO':'APAC',
'AQ':'APAC',
'BV':'APAC',
'IO':'APAC',
'TP':'APAC',
'FX':'EMEA',
'HM':'APAC',
'SH':'APAC',
'GS':'APAC',
'UM':'APAC',
'YU':'EMEA',
'RS':'EMEA',
'BQ':'LATAM',
'CW':'LATAM',
'BL':'LATAM',
'MF':'LATAM',
'ME':'EMEA'
}

country_full_name={
"AF":"Afghanistan",
"AL":"Albania",
"DZ":"Algeria",
"AS":"American Samoa",
"AD":"Andorra",
"AO":"Angola",
"AI":"Anguilla",
"AG":"Antigua and Barbuda",
"AR":"Argentina",
"AM":"Armenia",
"AW":"Aruba",
"AU":"Australia",
"AT":"Austria",
"AZ":"Azerbaijan",
"BS":"Bahamas, The",
"BH":"Bahrain",
"BD":"Bangladesh",
"BB":"Barbados",
"BY":"Belarus",
"BE":"Belgium",
"BZ":"Belize",
"BJ":"Benin",
"BM":"Bermuda",
"BT":"Bhutan",
"BO":"Bolivia",
"BA":"Bosnia and Herzegovina",
"BW":"Botswana",
"BR":"Brazil",
"VG":"British Virgin Islands",
"BN":"Brunei",
"BG":"Bulgaria",
"BF":"Burkina Faso",
"BI":"Burundi",
"KH":"Cambodia",
"CM":"Cameroon",
"CA":"Canada",
"CV":"Cape Verde",
"KY":"Cayman Islands",
"CF":"Central African Republic",
"TD":"Chad",
"CL":"Chile",
"CN":"China",
"CX":"Christmas Island",
"CC":"Cocos (Keeling) Islands",
"CO":"Colombia",
"KM":"Comoros",
"CG":"Congo, Republic of the",
"CK":"Cook Islands",
"CR":"Costa Rica",
"CI":"Cote d'Ivoire",
"HR":"Croatia",
"CU":"Cuba",
"CY":"Cyprus",
"CZ":"Czech Republic",
"DK":"Denmark",
"DJ":"Djibouti",
"DM":"Dominica",
"DO":"Dominican Republic",
"EC":"Ecuador",
"EG":"Egypt",
"SV":"El Salvador",
"GQ":"Equatorial Guinea",
"ER":"Eritrea",
"EE":"Estonia",
"ET":"Ethiopia",
"FK":"Falkland Islands (Islas Malvinas)",
"FO":"Faroe Islands",
"FJ":"Fiji",
"FI":"Finland",
"FR":"France",
"GF":"French Guiana",
"PF":"French Polynesia",
"GA":"Gabon",
"GM":"Gambia, The",
"GE":"Georgia",
"DE":"Germany",
"GH":"Ghana",
"GI":"Gibraltar",
"GR":"Greece",
"GL":"Greenland",
"GD":"Grenada",
"GP":"Guadeloupe",
"GU":"Guam",
"GT":"Guatemala",
"GN":"Guinea",
"GW":"Guinea-Bissau",
"GY":"Guyana",
"HT":"Haiti",
"VA":"Holy See (Vatican City)",
"HN":"Honduras",
"HU":"Hungary",
"IS":"Iceland",
"IN":"India",
"ID":"Indonesia",
"IR":"Iran",
"IQ":"Iraq",
"IE":"Ireland",
"IL":"Israel",
"IT":"Italy",
"JM":"Jamaica",
"JP":"Japan",
"JO":"Jordan",
"KZ":"Kazakhstan",
"KE":"Kenya",
"KI":"Kiribati",
"KP":"Korea, North",
"KR":"Korea, South",
"KW":"Kuwait",
"KG":"Kyrgyzstan",
"LA":"Laos",
"LV":"Latvia",
"LB":"Lebanon",
"LS":"Lesotho",
"LR":"Liberia",
"LY":"Libya",
"LI":"Liechtenstein",
"LT":"Lithuania",
"LU":"Luxembourg",
"MK":"Macedonia",
"MG":"Madagascar",
"MW":"Malawi",
"MY":"Malaysia",
"MV":"Maldives",
"ML":"Mali",
"MT":"Malta",
"MH":"Marshall Islands",
"MQ":"Martinique",
"MR":"Mauritania",
"MU":"Mauritius",
"YT":"Mayotte",
"MX":"Mexico",
"FM":"Micronesia, Federated States of",
"MD":"Moldova",
"MC":"Monaco",
"MN":"Mongolia",
"MS":"Montserrat",
"MA":"Morocco",
"MZ":"Mozambique",
"MM":"Myanmar (Burma)",
"NA":"Namibia",
"NR":"Nauru",
"NP":"Nepal",
"NL":"Netherlands",
"AN":"Netherlands Antilles",
"NC":"New Caledonia",
"NZ":"New Zealand",
"NI":"Nicaragua",
"NE":"Niger",
"NG":"Nigeria",
"NU":"Niue",
"NF":"Norfolk Island",
"MP":"Northern Mariana Islands",
"NO":"Norway",
"OM":"Oman",
"PK":"Pakistan",
"PW":"Palau",
"PA":"Panama",
"PG":"Papua New Guinea",
"PY":"Paraguay",
"PE":"Peru",
"PH":"Philippines",
"PN":"Pitcairn Islands",
"PL":"Poland",
"PT":"Portugal",
"PR":"Puerto Rico",
"QA":"Qatar",
"RE":"Reunion",
"RO":"Romania",
"RU":"Russia",
"RW":"Rwanda",
"KN":"Saint Kitts and Nevis",
"LC":"Saint Lucia",
"PM":"Saint Pierre and Miquelon",
"VC":"Saint Vincent and the Grenadines",
"SM":"San Marino",
"ST":"Sao Tome and Principe",
"SA":"Saudi Arabia",
"SN":"Senegal",
"SC":"Seychelles",
"SL":"Sierra Leone",
"SG":"Singapore",
"SK":"Slovakia",
"SI":"Slovenia",
"SB":"Solomon Islands",
"SO":"Somalia",
"ZA":"South Africa",
"ES":"Spain",
"LK":"Sri Lanka",
"SD":"Sudan",
"SR":"Suriname",
"SJ":"Svalbard",
"SZ":"Swaziland",
"SE":"Sweden",
"CH":"Switzerland",
"SY":"Syria",
"TW":"Taiwan",
"TJ":"Tajikistan",
"TZ":"Tanzania",
"TH":"Thailand",
"TG":"Togo",
"TK":"Tokelau",
"TO":"Tonga",
"TT":"Trinidad and Tobago",
"TN":"Tunisia",
"TR":"Turkey",
"TM":"Turkmenistan",
"TC":"Turks and Caicos Islands",
"TV":"Tuvalu",
"UG":"Uganda",
"UA":"Ukraine",
"AE":"United Arab Emirates",
"UK":"United Kingdom",
"GB":"United Kingdom",
"US":"United States",
"UY":"Uruguay",
"UZ":"Uzbekistan",
"VU":"Vanuatu",
"VE":"Venezuela",
"VN":"Vietnam",
"VI":"Virgin Islands",
"WF":"Wallis and Futuna",
"EH":"Western Sahara",
"WS":"Western Samoa",
"YE":"Yemen",
"ZR":"Zaire (Dem Rep of Congo)",
"ZM":"Zambia",
"ZW":"Zimbabwe",
"HK":"Hong Kong (China)",
"MO":"Macau (China)",
"AQ":"Antarctica",
"BV":"Bouvet Island",
"IO":"British Indian Ocean Territory",
"TP":"East Timor",
"FX":"France, Metropolitan",
"HM":"Heard Island and McDonald Islands",
"SH":"Saint Helena",
"GS":"South Georgia and the South Sandwich Islands ",
"UM":"United States Minor Outlying Islands",
"YU":"Yugoslavia",
"RS":"Serbia",
"BQ":"Bonaire, Sint Eustatius and Saba",
"CW":"Curacao",
"BL":"Saint Barthelemy",
"MF":"Saint Martin",
"ME":"Montenegro"
}
